###########################
#     FurgoPi-client      #
###########################

# Storage for the datapoints to be sent away
datapoints:
  # [String] Where to store it
  file: "storage/datapoints.jsonl"
  # [String] Where to store it
  path: "storage/"